export type DeputyDetails = {
  did: string;
  full_name: string;
  dep_status: string;
  birth_year: string;
  home_address: string;
  profession: string;
  phone: string;
  factions_short_name: string;
  faction_name: string;
  com_function: string;
  committee: string;
  email_work: string;
  email_personal: string;
  license: string;
  master: string;
  doctorat: string;
  facebook: string;
  tweeter: string;
  instagram: string;
  telegram: string;
  linkedIn: string;
  photo: string;
  curriculum_vitae: string;
  nr_mandates: string;
  mandates_details: string;
  conflicts: string;
  delegates: string;
  friendships: string;
  sold_absente_total: string;
  sold_sessions_total: string;
  investigate_comissions: string[];
  special_comissions: string[];
  author: string;
  sessions_present_absent: { presents: number; absents: number };
  declarations: string;
  voting: {
    pentru: string;
    contra: string;
    abtinut: string;
  };
};
