export type DeputyDetails = {
  did: string;
  fullName: string;
  depStatus: string;
  deputieFrom: string;
  deputieTo: string;
  birthYear: string;
  homeAddress: string;
  profession: string;
  phone: string;
  factionsShortName: string;
  factionName: string;
  comFunction: string;
  committee: string;
  emailWork: string;
  emailPersonal: string;
  license: string;
  master: string;
  doctorat: string;
  facebook: string;
  tweeter: string;
  instagram: string;
  telegram: string;
  linkedIn: string;
  photo: string;
  curriculumVitae: string;
  nrMandates: string;
  mandatesDetails: string;
  conflicts: string;
  delegates: string;
  friendships: string;
  soldAbsenteTotal: string;
  soldSessionsTotal: string;
  investigateComissions: string[];
  specialComissions: string[];
  author: string;
  questionsInterpelations: string;
  sessionsPresentAbsent: { presents: number; absents: number };
  declarations: string;
  voting: {
    pentru: string;
    contra: string;
    abtinut: string;
  };
};
